version: "3.7"

services:
  shitty-leaderboard-redis:
    image: redis:4.0
    volumes:
      - ./data/redis:/data
    entrypoint: redis-server --appendonly yes
    restart: always
    expose:
      - "65433"
    ports:
      - "65433:6379"
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
      interval: 10s
      timeout: 2s
      retries: 10